### ISSUE TITLE
Turn on pre-commit.ci

### ISSUE THREAD

**Issue by matthewfeickert** [ryancheley/the-well-maintained-test#24]
**Is your feature request related to a problem? Please describe.**
Not a problem, just that as you are already using `pre-commit` (:rocket:) you might as well take advantage of the wonderful [pre-commit.ci](https://pre-commit.ci/). :+1: 

**Describe the solution you'd like**
Turn on pre-commit.ci for the repo and add an update config for pre-commit.ci to the existing `.pre-commit-config.yaml`.

**Describe alternatives you've considered**
Running pre-commit in a separate GitHub Actions workflow, but that's the same thing and slower.

**Comment by ryancheley** [comment]
@matthewfeickert  I believe I've done this, but this is my first time using pre-commit.ci. The docs indicate:

>> configuration: zero configuration setup -- nothing is needed beyond the `.pre-commit-config.yaml` file you already have!

If there's something else that I'm missing let me know. Thanks for the tip / request!

**Comment by matthewfeickert** [comment]
> @matthewfeickert I believe I've done this

Yup, https://results.pre-commit.ci/latest/github/ryancheley/the-well-maintained-test/main exists now. :+1: It will now run on all PRs and if a commit in the PR doesn't pass the pre-commit checks it will push back changes that address it (if it can).

> but this is my first time using pre-commit.ci. The docs indicate:
> 
> > > configuration: zero configuration setup -- nothing is needed beyond the `.pre-commit-config.yaml` file you already have!
> 
> If there's something else that I'm missing let me know. Thanks for the tip / request!

You could add a `pre-commit.ci` status badge to the repo 

[![pre-commit.ci status](https://results.pre-commit.ci/badge/github/ryancheley/the-well-maintained-test/main.svg)](https://results.pre-commit.ci/latest/github/ryancheley/the-well-maintained-test/main)

and if you'd like `pre-commit.ci` to open up PRs on `the-well-maintained-test` to update the pre-commit hooks in your `.pre-commit-config.yaml` on a scheduled basis (every week, month, or quarter) you can add a section to the top of your `.pre-commit-config.yaml` to configure this (more [details on the CI config in the docs](https://pre-commit.ci/#configuration)). Here's an [example from `pyhf`](https://github.com/scikit-hep/pyhf/blob/b798ef23c77db6b1d6d606f4b360a5f47fd63dd2/.pre-commit-config.yaml#L1-L3).

**Comment by ryancheley** [comment]
closed with 609ea77
