### ISSUE TITLE
Helper method _get_test_files cannot find tests.py

### ISSUE THREAD

**Issue by omerfarukabaci** [ryancheley/the-well-maintained-test#26]
## Description
While examining `helpers.py` I saw the regex search below:

- `re.search(r"test_(.*).py", i.get("path"))`

It currently cannot find `tests.py` file, so the regex above can be rewritten as:

- `re.search(r"test(s|_(.*)).py", i.get("path"))`

## To Reproduce
1. For example: `the-well-maintained-test url https://github.com/revsys/django-friendship` reports that there is no tests, even though it exists [here](https://github.com/revsys/django-friendship/blob/main/friendship/tests/tests.py).

## Expected behavior
`tests.py` should be found by the helper method.

Thanks for maintaining this package, it seems promising! 🚀

**Comment by ryancheley** [comment]
@omerfarukabaci thanks for the bug report and the new regex to fix it! 🚀

I’ll work on incorporating that code and a fix this weekend.
