### ISSUE TITLE
Update CLI to create the auth.json file based on a passed command

### ISSUE THREAD

**Issue by ryancheley** [ryancheley/the-well-maintained-test#7]
Currently if a user wants to authenticate against the GitHub API they have to copy the `example_auth.json` file and add their Git Hub Personal Token. The user should be able to pass a command via the tool to prompt for the token and write it to disk. 

**Describe the solution you'd like**
update the CLI so that this command works (or something similar):

```
the-well-maintained-test auth
```

A couple of other packages already do this ([toggl-to-sqlite](https://github.com/ryancheley/toggl-to-sqlite) and [github-to-sqlite](https://github.com/dogsheep/github-to-sqlite))

**Describe alternatives you've considered**
The current workaround of updating manually is *fine* but it can make it more difficult for users to not hit the rate limits of the GitHub API

**Additional context**

**Comment by ryancheley** [comment]
I am a bit worried that this will change the API and introduce breaking changes and will force me to bump the version to 1.0 way before I'm ready 👎

**Comment by matthewfeickert** [comment]
I suspect that Issue #10 is really just an API rate limit Issue and so related to this Issue.

> I am a bit worried that this will change the API and introduce breaking changes and will force me to bump the version to 1.0 way before I'm ready

As a stranger on the internet I'm not going to tell you how strictly you should follow SemVer for your personal projects, but I certainly don't think anyone would fault you for introducing breaking API changes in a minor release in a ZeroVer project. :)
